package oracle.dev.demo.model.views.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 20 14:40:18 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ChoicesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ChoicesVOImpl() {
    }
}

